### PR TITLE
Update URL py5.ixora.io -> py5coding.org

### PR DESCRIPTION
**Pull request by villares**

### CODE REVIEW

**Review by hx2A — DISMISSED** [review]

**Comment by hx2A** [comment]
Thank you for noticing this!

**Comment by villares** [comment]
sorry for this, I think I messed up with the branches :-S

**Comment by hx2A** [comment]
@villares , github is being uncooperative right now. It looks like you pushed a lot of example code to the previous PR that made that URL change. Is that correct? I haven't quite mastered reviewing PRs, or even have a half understanding of them.

**Comment by villares** [comment]
Yeah, that's it.
I could close this and restart on a clean branch I suppose...

**Comment by hx2A** [comment]
This PR is fine, but next time, it is probably better to start a new PR for each separate thing.

Can you tell me about this? This contains all the ported example code, right?

**Comment by villares** [comment]
I usually make distinct branches, I even teach this to my students!

But this time I messed up twice... first I made the URL correction in main. And made the PR.

Then I have this branch with the Processing Python mode examples I'm working on converting and for some reason I wanted to merge them to main and start over, I don't even remember why. So that was it.

I'm not even ready to share the conversion yet.

**Review by hx2A — APPROVED** [review]
Github doesn't even show me the files that changed

**Comment by hx2A** [comment]
OK, I don't understand what happened. There isn't more example code or anything different. @villares, can you create a new PR with the new example code you worked on? It isn't your fault, Github doesn't seem to like that you reopened a previous PR.

**Comment by villares** [comment]
Sure, I was thinking of some way of "testing", running many examples before sending the examples, but I'll do it.

**Comment by hx2A** [comment]
If it helps, there is code that is used to run all of the example code you see in the reference docs.

https://github.com/py5coding/py5generator/blob/main/py5_docs/scripts/run_example_code.py

Most of that is specific to the reference docs and the Documetation files though. The part that might be useful is here:

https://github.com/py5coding/py5generator/blob/main/py5_resources/py5_module/py5_tools/testing.py

That assumes module mode. Is your example code in imported mode? If so, you might benefit from making calls to `run_code()` in imported.py:

https://github.com/py5coding/py5generator/blob/main/py5_resources/py5_module/py5_tools/imported.py

**Comment by villares** [comment]
The examples are imported mode, as they are the Processing Python mode direct coversion... I'll have to tinker with that! thanks!

**Pull request merged**
